name: Terraform deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  AWS_REGION: "us-west-1"
  TF_VERSION: "1.5.0"
  
permissions:
  id-token: write
  contents: write
  pull-requests: write
  
jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
        # Step 2: Install Git LFS
      - name: Install Git LFS
        run: |
          git lfs install

      # Step 3: Track Large Files with Git LFS
      - name: Track Large Files with Git LFS
        run: |
          git lfs track "Infra/.terraform/providers/registry.terraform.io/hashicorp/aws/5.87.0/linux_amd64/terraform-provider-aws_v5.87.0_x5"
          git add .gitattributes  # Make sure to add the .gitattributes file that git-lfs uses

      # Step 4: Commit Changes (If Needed)
      - name: Commit Changes (if any)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Add Terraform provider binary to Git LFS" || echo "No changes to commit"

      # Step 5: Push Changes to GitHub
      - name: Push Changes
        run: |
          git push origin ${{ github.event.pull_request.head.ref || github.ref }}


      # Set up AWS credentials
      - name: Set up AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::877786395093:role/github-oidc-vamsee
          aws-region: us-west-1

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Initialize Terraform
      - name: Terraform Init
        run: |
          cd Infra
          terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: |
          cd Infra
          terraform validate

      # Run Terraform Plan
      - name: Terraform Plan
        run: |
          cd Infra
          terraform plan -var-file="../environments/dev/terraform.tfvars" -out=tfplan
          
      - name: Generate Markdown with Terraform Docs
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: ./Infra
          output-file: README.md
          output-method: inject
          git-push: true
          config-file: .terraform-docs.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 10: Configure Git to Commit Generated Docs
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 11: Add README.md as PR Comment (Using Sticky Comment)
      - name: Posting README.md as PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          header: "Terraform Documentation "
          path: "./Infra/README.md"

      # Step 12: Apply Terraform Changes on PR Merge
      - name: Applying Terraform after PR Merge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd ./Infra
          terraform init
          terraform apply -auto-approve tfplan
